### ISSUE TITLE
Feature to ease the download of the material 

### ISSUE THREAD

**Issue by KevCaz** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#10]
I propose to add a new field in the yaml header that would ease the way the reader can dowload th material. Below an example of what the yaml header shuold look like:

```
download:  
  - text: "mat_1"
    icon: "fa fa-code"
    href: "cool.jpg" 
  - text: "mat_2"
    icon: "fa fa-archive"
    href: "cool.zip"
```

Then links are added to the post below the keywords. 
By default the .Rmd and R files must be available.
